### ISSUE TITLE
[SRV02] Set up a Flask API Server

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/piPDU#1]
## Description

The piPDU Server component needs to host an API Server which will expose endpoints to toggle on/off any of the 16 power plugs.

## Tasks

- [ ] Set up a basic Flask API Server
- [ ] Set up the routes for the power plug endpoints
- [ ] Set up dummy functions to toggle the plugs on/off (`print (f"Plug is {status}")`
