### ISSUE TITLE
[CTRL01] Build the enclosure

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/piPDU#3]
## Description

The piPDU controller will be housed in a 2U rack case (TODO Add link).  
The rack case needs 16 holes drilled in the front to house the buttons as well as a cutout for the LCD screen.  
All the components need to be wired up.

## Tasks

- [x] Drill the 16 holes for the buttons
- [x] Cut out the hole for the LCD Screen
- [x] Solder the i2c controller to the LCD screen
- [x] Wire up the LED matrix
- [x] Wire up the button matrix
- [ ] Wire up the LCD to the Pi
- [ ] Make a proto-board to connect the pi to all the components
- [ ] Create a BOM
