### ISSUE TITLE
[SRV01] Build the Enclosure

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/piPDU#4]
## Description

The piPDU serverwill be housed in a 5U rack case (TODO Add link).  
The rack case needs 16 holes drilled in the front to house the power plugs.  
All the components need to be wired up.

## Tasks

- [ ] Drill the 16 holes for the power plugs
- [ ] Wire up the relay board to the Arduino
- [ ] Wire up the current sensors to the Arduino
- [ ] Connect the Arduino to the Pi
- [ ] Connect the power plugs to the relay board and the current sensors
- [ ] Make a proto-board to connect all the components
- [ ] Create a BOM
